// Mock data for immediate visual validation
export const mockDigest = {
  id: "mock-digest-1",
  date: new Date().toISOString().split("T")[0],
  title: "Daily AI Digest",
  summary: "Your daily curated AI news - the essential updates in 3 minutes.",
  published_at: new Date().toISOString(),
};

export const mockItems = [
  {
    id: "item-1",
    digest_id: "mock-digest-1",
    title: "OpenAI Announces GPT-5 with Revolutionary Reasoning Capabilities",
    url: "https://techcrunch.com/openai-gpt5",
    source: "TechCrunch",
    snippet: "The latest model shows unprecedented performance on complex reasoning tasks, marking a new era in artificial intelligence development.",
    content_md: "OpenAI has unveiled GPT-5, their most advanced language model to date. The new model demonstrates remarkable improvements in complex reasoning, mathematical problem-solving, and creative tasks. Early benchmarks suggest performance gains of 40-60% over GPT-4 across various evaluation metrics.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop",
    tags: ["AI Models", "OpenAI"],
    rank: 1,
    read_time_minutes: 3,
  },
  {
    id: "item-2",
    digest_id: "mock-digest-1",
    title: "EU AI Act: New Regulations Set to Transform Tech Industry",
    url: "https://reuters.com/eu-ai-act",
    source: "Reuters",
    snippet: "European Union finalizes comprehensive AI regulations that will reshape how companies develop and deploy AI systems globally.",
    content_md: "The European Union has officially adopted the AI Act, marking a historic moment in technology regulation. The legislation establishes a risk-based framework for AI systems, with strict requirements for high-risk applications in healthcare, law enforcement, and critical infrastructure.",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop",
    tags: ["Regulation", "Policy"],
    rank: 2,
    read_time_minutes: 4,
  },
  {
    id: "item-3",
    digest_id: "mock-digest-1",
    title: "Anthropic Raises $2B in Latest Funding Round",
    url: "https://bloomberg.com/anthropic-funding",
    source: "Bloomberg",
    snippet: "The AI safety-focused startup continues rapid expansion with new investment from major tech players.",
    content_md: "Anthropic, the AI safety company founded by former OpenAI researchers, has closed a $2 billion funding round. The investment will fuel continued development of Claude and research into AI alignment and interpretability.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&auto=format&fit=crop",
    tags: ["Startups", "Funding"],
    rank: 3,
    read_time_minutes: 2,
  },
  {
    id: "item-4",
    digest_id: "mock-digest-1",
    title: "Breakthrough in AI Drug Discovery: New Treatment Identified",
    url: "https://nature.com/ai-drug-discovery",
    source: "Nature",
    snippet: "Machine learning algorithms identify promising compounds for treating rare diseases in record time.",
    content_md: "Researchers have used AI to identify a potential treatment for a rare genetic disorder in just 18 months, compared to the typical 5-10 year timeline. The breakthrough demonstrates the transformative potential of machine learning in pharmaceutical research.",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop",
    tags: ["Research", "Healthcare"],
    rank: 4,
    read_time_minutes: 5,
  },
  {
    id: "item-5",
    digest_id: "mock-digest-1",
    title: "Microsoft Copilot Gets Major Update with New Features",
    url: "https://theverge.com/microsoft-copilot",
    source: "The Verge",
    snippet: "New capabilities include advanced code generation and seamless integration across Office suite applications.",
    content_md: "Microsoft has released a significant update to Copilot, bringing enhanced code generation, better context understanding, and deeper integration with Microsoft 365 applications. The update also introduces new voice interaction capabilities.",
    image_url: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=800&auto=format&fit=crop",
    tags: ["Tools", "Microsoft"],
    rank: 5,
    read_time_minutes: 3,
  },
  {
    id: "item-6",
    digest_id: "mock-digest-1",
    title: "Google DeepMind Achieves New Milestone in Protein Folding",
    url: "https://wired.com/alphafold-3",
    source: "Wired",
    snippet: "AlphaFold 3 can now predict protein interactions with unprecedented accuracy, opening doors for medical research.",
    content_md: "DeepMind's AlphaFold 3 represents a major leap forward in computational biology. The system can now accurately predict how proteins interact with other molecules, including DNA, RNA, and small molecules, which is crucial for drug design.",
    image_url: "https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&auto=format&fit=crop",
    tags: ["Research", "Google"],
    rank: 6,
    read_time_minutes: 4,
  },
  {
    id: "item-7",
    digest_id: "mock-digest-1",
    title: "AI-Powered Autonomous Vehicles Pass 1 Million Mile Mark",
    url: "https://arstechnica.com/waymo-milestone",
    source: "Ars Technica",
    snippet: "Waymo's self-driving fleet reaches historic milestone with impressive safety record in urban environments.",
    content_md: "Waymo has announced that its autonomous vehicle fleet has completed over one million miles of fully driverless operation in urban environments. The company reports zero at-fault accidents during this period, demonstrating significant progress in self-driving technology.",
    image_url: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop",
    tags: ["Startups", "Autonomous"],
    rank: 7,
    read_time_minutes: 3,
  },
  {
    id: "item-8",
    digest_id: "mock-digest-1",
    title: "Open Source AI Models Challenge Commercial Offerings",
    url: "https://venturebeat.com/open-source-ai",
    source: "VentureBeat",
    snippet: "Community-developed models are closing the gap with proprietary systems, democratizing AI access worldwide.",
    content_md: "The open-source AI community has made remarkable strides, with models like Llama 3 and Mistral achieving performance levels competitive with leading commercial offerings. This democratization of AI capabilities is reshaping the industry landscape.",
    image_url: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&auto=format&fit=crop",
    tags: ["AI Models", "Open Source"],
    rank: 8,
    read_time_minutes: 4,
  },
];

export const mockCategories = [
  "All",
  "AI Models",
  "Regulation",
  "Startups",
  "Research",
  "Tools",
];
